Feature
thrashches/gpx_routes_backend pull request #5
Opened 2023-10-10 11:32 UTC by atatriismine

Изменены названия с core на gpx_routes_backend, исключены .env, изменен README, добавлено описание

2023-10-10 14:17 UTC, thrashches commented
1. В [Readme](https://github.com/thrashches/gpx_routes_backend/tree/feature#:~:text=2%20days%20ago-,README.md,-Merge%20branch%20%27dev) по прежнему кривая структура. Возможно должен стоять не `bash` как синтаксис, а `Output` как в примерах ниже в том же файле
2. Настрой `.gitignore`. Не должны бинари и `__pycache__` утекать в репозиторий. Каждый такой файл в отличие от текстового начинает занимать много места. При их изменении время операций push/pull увеличивается.

2023-10-10 14:22 UTC, thrashches commented on gpx_dev/api/__pycache__/__init__.cpython-311.pyc
Это надо убрать. Все такие файлы должны быть в `.gitignore`

2023-10-10 14:22 UTC, thrashches commented on gpx_dev/start.sh
>  python manage.py createsuperuser --no-input
Нужно ли при каждом запуске создавать суперпользователя? Это один раз админом делается, дальше все через админку.

2023-10-10 16:05 UTC, atatriismine commented on gpx_dev/api/__pycache__/__init__.cpython-311.pyc
Исправил, скорректировал .gitignore

2023-10-10 21:45 UTC, thrashches requested changes
Файл `.gitignore` тоже должен лежать в проекте.

2023-10-10 21:45 UTC, thrashches commented on gpx_dev/users/models.py
> +    password = models.CharField(max_length=128)
Это поле уже есть в базовой модели

2023-10-10 21:45 UTC, thrashches commented on gpx_dev/users/models.py
> +    is_active = models.BooleanField(default=True)
И это тоже

2023-10-10 21:45 UTC, thrashches commented on gpx_dev/users/models.py
> +    is_staff = models.BooleanField(default=False)
и это

2023-10-10 21:45 UTC, thrashches commented on gpx_dev/users/models.py
> +    date_joined = models.DateTimeField(default=timezone.now)
и это

2023-10-10 21:45 UTC, thrashches commented on gpx_dev/users/admin.py
> +admin.site.register(User)
Используй `ModelAdmin` - классы для добавления сложных моделей. У юзеров есть `UserAdmin`, в котором реализована форма для создания пароля, и тд. Иначе это все придется руками описывать. Посмотри пример [в документации](https://docs.djangoproject.com/en/4.2/topics/auth/customizing/#extending-the-existing-user-model)

2023-10-10 21:45 UTC, thrashches commented on gpx_dev/users/models.py
> +    username_validator = UnicodeUsernameValidator()
Зачем? Мы это поле не юзаем.

2023-10-10 21:45 UTC, thrashches commented on gpx_dev/users/models.py
> +        username = nickname
Это костыль. Можно сделать проще, прописав 
```python
class User(AbstractUser):
    username = None
    ...
```

2023-10-11 08:57 UTC, atatriismine commented on gpx_dev/users/models.py
> +    password = models.CharField(max_length=128)
убираю поле password

2023-10-11 08:58 UTC, atatriismine commented on gpx_dev/users/models.py
> +    is_active = models.BooleanField(default=True)
убираю поле date_joined и is_active

2023-10-11 08:58 UTC, atatriismine commented on gpx_dev/users/models.py
> +    is_staff = models.BooleanField(default=False)
убираю поле is_staff

2023-10-11 09:38 UTC, atatriismine commented on gpx_dev/users/models.py
> +    username_validator = UnicodeUsernameValidator()
я изменю имя переменной с username_validator на nickname_validator, но при этом оставить валидацию

2023-10-11 09:42 UTC, atatriismine commented on gpx_dev/users/models.py
> +        username = nickname
Провобал, падают тесты. 
Если в менеджере не определять username, то выпадает ошибка. 
Как вариант попробовать тогда наследоваться не от AbstractUser, а выше, от AbstractBaseUser и PermissionsMixin, но тогда нужно будет все поля которые есть в  AbstractUser определить в новой модели. 
Одно изменение с username на nickname ломает все, поэтому закостылил. Понимаю, что так делать неправильно, но не знаю как по другому сделать

2023-10-14 20:04 UTC, thrashches requested changes

2023-10-14 20:04 UTC, thrashches commented on gpx_dev/users/models.py
> +    date_joined = models.DateTimeField(default=timezone.now)
Вот такое решение должно работать
```python
class User(AbstractUser):
    email = models.EmailField(unique=True, verbose_name='Email')
    USERNAME_FIELD = 'email'
    username = None

    objects = UserManager()

    nickname = models.CharField(
        max_length=255, 
        verbose_name='Nickname', 
        unique=True
    )

    REQUIRED_FIELDS = [
        'nickname',
    ]
```
Нет никакого смысла переписывать модель полностью.

2023-10-14 20:04 UTC, thrashches commented on gpx_dev/users/models.py
> +    status = models.BooleanField(choices=Status.choices, default=Status.ACTIVE)
Не совсем понятно зачем это поле. У тебя проверка на уникальность пары `follower -> followee` и так есть. Какой смысл хранить инфу о неактивной подписке? Нет подписки - нет записи.

2023-10-14 20:04 UTC, thrashches commented on gpx_dev/users/models.py
> +    followee = models.ForeignKey(
- [followee](https://translate.google.com/?sl=en&tl=ru&text=followee&op=translate)
- [follower](https://translate.google.com/?sl=en&tl=ru&text=follower&op=translate)
Оба слова переводятся одинаково. Я бы одно переименовал в follows.

2023-10-14 20:04 UTC, thrashches commented on gpx_dev/users/models.py
> +        unique_together = (
Это `deprecated` опция, [ее скоро уберут](https://docs.djangoproject.com/en/4.2/ref/models/options/#unique-together) юзай `UniqueConstraint`.

2023-10-16 18:40 UTC, atatriismine commented on gpx_dev/users/models.py
> +    status = models.BooleanField(choices=Status.choices, default=Status.ACTIVE)
тут я думал делать активна/неактивна в том плане, что пользователь мог бы заново активировать подписку свою, и можно было бы иметь историю каких либо подписок. Условно я на человека подписался, потом деактивировал подписку, затем для того чтобы возобновить, можно было бы просто взять список неактивных. Но так, как ты предлагаешь, даже проще, при отписке запись просто будет удаляться, а то у меня с этими статусами логика сломалась, нужно было переделывать. Оно и так переделывать, но проще)))

2023-10-16 19:05 UTC, atatriismine commented on gpx_dev/users/models.py
> +    followee = models.ForeignKey(
[из этой либы](https://github.com/revsys/django-friendship/blob/fa842d25f761accdc32dbb387dd777180406af3b/friendship/models.py#L469C28-L469C28) я пытался взять, тут я не выдумывал)

2023-10-16 20:03 UTC, atatriismine commented on gpx_dev/users/models.py
> +        unique_together = (
Исправил, спасибо

2023-10-26 06:10 UTC, thrashches commented
Надо будет поменять `UserChangeForm` для админки, в связи с тем, что `username` теперь `nickname`.

2023-10-26 06:10 UTC, merged